name: Render Deployment
on:
  workflow_dispatch:
    input:
      environment:
        description: 'Select environment'
        required: true
        type: environment

jobs:
  Render-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Render deployment
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"